ci: fix main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,9 +25,7 @@ jobs:
 
       - name: Run Lint (flake8)
         run: |
-          # Остановит сборку, если есть ошибки синтаксиса
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-          # Предупреждения (стандарт PEP8)
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
   build-docker:
@@ -57,7 +55,7 @@ jobs:
           # 1. Создаем директорию для кэша pydrive2
           mkdir -p ~/.cache/pydrive2fs/710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com/
           
-          # 2. Генерируем json-файл с токеном вручную
+          # 2. Генерируем json-файл с токеном
           echo "{
             \"access_token\": \"dummy\",
             \"client_id\": \"$GDRIVE_CLIENT_ID\",
@@ -65,10 +63,6 @@ jobs:
             \"refresh_token\": \"$GDRIVE_REFRESH_TOKEN\",
             \"token_expiry\": \"2020-01-01T00:00:00Z\",
             \"token_uri\": \"https://oauth2.googleapis.com/token\",
-            \"user_agent\": null,
-            \"revoke_uri\": \"https://oauth2.googleapis.com/revoke\",
-            \"id_token\": null,
-            \"id_token_jwt\": null,
             \"token_response\": {
               \"access_token\": \"dummy\",
               \"expires_in\": 3599,
@@ -80,16 +74,22 @@ jobs:
               \"https://www.googleapis.com/auth/drive\",
               \"https://www.googleapis.com/auth/drive.appdata\"
             ],
-            \"token_info_uri\": \"https://oauth2.googleapis.com/tokeninfo\",
             \"invalid\": false,
             \"_class\": \"OAuth2Credentials\",
             \"_module\": \"oauth2client.client\"
           }" > ~/.cache/pydrive2fs/710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com/default.json
 
-          # 3. Теперь DVC "подхватит" этот файл и не полезет в браузер
+          # 3. Скачиваем данные
           dvc pull
+
+      - name: Debug file structure
+        run: |
+          echo "Current directory structure:"
+          ls -R
+          echo "Checking data/models folder:"
+          ls -la data/models || echo "Folder data/models not found"
 
       - name: Build Docker image
         run: |
-          # Теперь указываем правильный путь к файлу в корне
+          # Убеждаемся, что Dockerfile в корне и контекст сборки верный
           docker build -t energy-api-service:latest -f Dockerfile .
